# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       khotkeys

# >> macros
# << macros

Summary:    KHotkeys
Version:    5.0.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  khotkeys.yaml
Source101:  khotkeys-rpmlintrc
Requires:   kf5-filesystem
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5PrintSupport)
BuildRequires:  pkgconfig(Qt5X11Extras)
BuildRequires:  kf5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  kglobalaccel-devel
BuildRequires:  ki18n-devel
BuildRequires:  kio-devel
BuildRequires:  kxmlgui-devel
BuildRequires:  kdelibs4support-devel
BuildRequires:  kdbusaddons-devel
BuildRequires:  kcmutils-devel
BuildRequires:  plasma-devel
BuildRequires:  plasma-workspace-devel
BuildRequires:  libX11-devel

%description
KHotkeys


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
The %{name}-devel package contains the files necessary to develop applications
that use %{name}.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
%kf5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kf5_make_install
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%doc COPYING
%{_kf5_libdir}/libkhotkeysprivate.so.*
%{_kf5_plugindir}/*
%{_kf5_sharedir}/khotkeys
%{_kf5_servicesdir}/*
%{_kf5_dbusinterfacesdir}/*.xml
%{_kf5_htmldir}/en/kcontrol/khotkeys
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_kf5_cmakedir}/KHotKeysDBusInterface
# >> files devel
# << files devel
